sudo: required
services:
  - docker

before_install:
  - docker build -t matinsasan/sample-docker-react -f Dockerfile.dev .

script:
  - docker run matinsasan/sample-docker-react npm test -- --coverage
